### ISSUE TITLE
Add transformer for picking a single item from store

### ISSUE THREAD

**Issue by Amaljith-K** [bigbinary/babel-preset-neeto#10]
Right now, zustand pick operator returns an object containing the picked keys. It is inefficient for picking a single item from the store.
<table>
<tr>
<td colspan="2"><b>Current workaround</b></td>
</tr>
<tr>
<th>User's code</th>
<th>Transpiled code</th>
</tr>
<tr>
<td>

```js
const { setUser } = useUserStore.pick();
```

</td>
<td>

```js
import { shallow } from "zustand/shallow";

const { setUser } = useUserStore(
  store => ({ setUser: store.setUser }),
  shallow
);
```
</td>
</tr>
<tr>
<td>

```js
const { name } = useUserStore.pick("user");
```

</td>
<td>

```js
import { shallow } from "zustand/shallow";

const { name } = useUserStore(
  store => ({ name: store.user?.name }),
  shallow
);
```
</td>
</tr>
<tr>
<td colspan="2"><b>Proposed transformer</b></td>
</tr>
<tr>
<td>

```js
const setUser = useUserStore.pickFrom();
```

</td>
<td>

```js
const setUser = useUserStore(store => store.setUser);
```
</td>
</tr>
<tr>
<td>

```js
const name = useUserStore.pickFrom("user");
```

</td>
<td>

```js
const name = useUserStore(store => store.user?.name);
```
</td>
</tr>
</table>

@ajmaln _a please assign someone to work on this.

**Comment by ajmaln** [comment]
@Calvinwilson99 _a
