### ISSUE TITLE
Add ability to use "useStore" as the variable name of the store

### ISSUE THREAD

**Issue by bonniesimon** [bigbinary/babel-preset-neeto#17]
Description:
- Update the regex, used to check the store name, to accept `useStore`

Currently the following approach causes the following error:

```js
  const { status, error } = useStore.pick();
```

![image](https://github.com/bigbinary/babel-preset-neeto/assets/49012815/f05dc54c-6723-48d2-92db-4e06882e2373)

 In the [source](https://github.com/bigbinary/babel-preset-neeto/blob/2ebd7707aae55e6150ef4765c0fba51c7f60d1dd/src/plugins/zustand-pick/constants.js#L35):

```js
// from this
test(/^use[a-zA-Z0-9]+Store$/)

// to this
test(/^use[a-zA-Z0-9]*Store$/)
```

cc: @Amaljith-K

**Comment by Amaljith-K** [comment]
@ajmaln Also check whether it is feasible to allow member expressions like:
```js
const { status } = mediaRecorder.useStore();
```
